version: 2.1

parameters:
  deploy-project-id:
    type: string
    default: "langadventure-shared-common"

  action:
    type: enum
    enum: [cicd, force-deploy]
    default: cicd

jobs:
  deploy:
    docker:
      - image: cimg/gcp:2023.09
    parameters:
      package_name:
        type: string
        default: ${CIRCLE_PROJECT_REPONAME}
    steps:
      - checkout
      - run:
          name: Configure Python to use Artifact Registry
          command: |
            echo $GOOGLE_CREDENTIALS_JSON > ./gcloud-key.json
            gcloud auth activate-service-account --key-file=./gcloud-key.json
            echo $CIRCLE_BUILD_NUM
            echo "$CIRCLE_BRANCH" | tr / _
 
workflows:
  build-and-deploy:
    when:
      equal: [ cicd, << pipeline.parameters.action >> ]
    jobs:
      - deploy:
          context:
            - gcp
          # filters:
          #   branches:
          #     only: main

  force-deploy:
    when:
      equal: [ force-deploy, << pipeline.parameters.action >> ]
    jobs:
      - deploy:
          context:
            - gcp