version: 2.1

orbs:
  python: circleci/python@3.0.0

parameters:
  deploy-project-id:
    type: string
    default: "langadventure-shared-common"

  action:
    type: enum
    enum: [cicd, force-deploy]
    default: cicd

jobs:
  build_and_test:
    docker:
      - image: ${GITHUB_DOCKER_HOST}/${GITHUB_DOCKER_NAMESPACE}/docker-gcp-poetry:3.12.1
        auth:
          username: $GITHUB_READ_PACKAGES_USER
          password: $GITHUB_READ_PACKAGES_TOKEN
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Configure Docker to use Artifact Registry
          command: |
            echo $GOOGLE_CREDENTIALS_JSON > ./gcloud-key.json
            gcloud auth activate-service-account --key-file=./gcloud-key.json
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run linter
          command: |
            eval $(poetry env activate)
            poetry run poe lint
      - run:
          name: Run type checker
          command: |
            eval $(poetry env activate)
            poetry run pyright
      - run:
          name: Run unit tests
          command: poetry run pytest --junitxml=reports/junit.xml

  deploy:
    docker:
      - image: ${GITHUB_DOCKER_HOST}/${GITHUB_DOCKER_NAMESPACE}/docker-gcp-poetry:3.12.1
        auth:
          username: $GITHUB_READ_PACKAGES_USER
          password: $GITHUB_READ_PACKAGES_TOKEN
    parameters:
      package_name:
        type: string
        default: ${CIRCLE_PROJECT_REPONAME}
    steps:
      - checkout
      - run:
          name: Configure Python to use Artifact Registry
          command: |
            echo $GOOGLE_CREDENTIALS_JSON > ./gcloud-key.json
            gcloud auth activate-service-account --key-file=./gcloud-key.json
      - when:
          condition:
            equal: [ force-deploy, << pipeline.parameters.action >> ]
          steps:
            - run:
                name: Update version
                command: |
                  poetry version $(poetry version -s).b$CIRCLE_BUILD_NUM
      - run:
          name: Build
          command: |
            poetry build
      - run:
          name: Publish
          command: |
            poetry publish -r gcp-pub
      - run:
          name: Revoke Auth
          command: |
            gcloud auth revoke --all
 
workflows:
  build-and-test:
    when:
      and:
        - not:
            equal: [ force-deploy, << pipeline.parameters.action >> ]
        - not:
            equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build_and_test:
          context:
            - gcp
            - github

  build-and-deploy:
    when:
      equal: [ cicd, << pipeline.parameters.action >> ]
    jobs:
      - deploy:
          context:
            - gcp
            - github
          filters:
            branches:
              only: main

  force-deploy:
    when:
      equal: [ force-deploy, << pipeline.parameters.action >> ]
    jobs:
      - deploy:
          context:
            - gcp
            - github
